name: Build & Package using Docker example

on:
  workflow_dispatch:
    secrets:
      GITHUB_TOKEN:
        required: true
    inputs:
      DOCKER_OS_IMAGE:
        description: Docker OS Image
        required: true
        type: choice
        options:
        - debian
        - fedora
        - arch
        default: debian
      SOURCE_CODE_URL:
        description: Source Code Repo URL
        required: true
        default: https://github.com/1ndev-ui/TWRP_CG65_device_tree/
      SOURCE_CODE_BRANCH:
        description: Source Code Repo Branch
        required: true
        default: main
      MAKE_FLAGS:
        description: (optional) Add additional make flags
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Set Environment Variables
      run: |
        echo "WORK_WEEK=$(date "+%yWW%W.%u")" >> $GITHUB_ENV
        echo "TIMEZONE=$(date "+%Z")" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)" >> $GITHUB_ENV
        echo "REPO_URL=${{ github.event.inputs.SOURCE_CODE_URL }}" >> $GITHUB_ENV
        echo "REPO_NAME=$(echo ${{ github.event.inputs.SOURCE_CODE_URL }} | awk -F'/' '{ print $5 }')" >> $GITHUB_ENV
        echo "REPO_BRANCH=${{ github.event.inputs.SOURCE_CODE_BRANCH }}" >> $GITHUB_ENV

    - name: Create Timestap & Set Working Directory
      run: |
        echo "REPO_NAME_TIMESTAMP=$(echo ${{ env.REPO_NAME }} | awk '{ print $1 "-" ENVIRON["REPO_BRANCH"] "-" ENVIRON["WORK_WEEK"] "." ENVIRON["TIMEZONE"] "-" ENVIRON["COMMIT_HASH"] }')" >> $GITHUB_ENV
        echo "REPO_PWD=${{ github.workspace }}/${{ env.REPO_NAME }}" >> $GITHUB_ENV
        echo "CHECKOUT_REPO=$(echo ${{ env.REPO_URL }} | awk -F 'https://github.com/' '{gsub(/\/$/, "", $2); print $2}')" >> $GITHUB_ENV

    - name: Display Environment Parameters
      run: |
        echo ""
        echo "${{ env.WORK_WEEK }} ${{ env.TIMEZONE }}"
        echo ""
        echo "Repo Name: ${{ env.REPO_NAME }}"
        echo "Repo Branch: ${{ env.REPO_BRANCH }}"
        echo "Repo URL: ${{ env.REPO_URL }}"
        echo "Hash: ${{ env.COMMIT_HASH }}"
        echo ""
        echo "Timestamp:"
        echo "${{ env.REPO_NAME_TIMESTAMP }}"
        echo ""
        echo "Workspace Directory:"
        echo "${{ env.REPO_PWD }}"
        echo ""
        echo "Additional Make Flags:"
        echo "${{ inputs.MAKE_FLAGS }}"
        echo ""

    - name: Self Checkout
      uses: actions/checkout@v4

    - name: Checkout Source Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ env.CHECKOUT_REPO }}
        ref: ${{ env.REPO_BRANCH }}
        path: ${{ env.REPO_PWD }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare the environment
      run: |
        sudo apt update -y && sudo apt upgrade -y
        sudo apt install git docker.io

    - name: Initalize Docker Environment
      run: |
        echo ""
        docker images
        echo ""
        docker ps
        echo ""
      working-directory: ${{ env.REPO_PWD }}

#    - name: Clone source code
#      run: |
#        git clone ${{ inputs.SOURCE_CODE_URL }} -b ${{ inputs.SOURCE_CODE_BRANCH }} ./${{ env.SOURCE_CODE_REPO_NAME }}



    - name: Upload compiled build as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME_TIMESTAMP }}
        path: ${{ env.REPO_PWD }}build/*

    - name: Clean Up
      if: always()
      run:  |
        cd ${{ github.workspace }}
        sudo rm -r *
        df -h
        ls -h
